### ISSUE TITLE
desktop launcher file

### ISSUE THREAD

**Issue by xiphosurus** [jj9btcproj/CryptoCoin-Price-Indicator#1]
There is an issue with the file "bitcoin-price-indicator.deskto.desktop". Firstly, it looks misnamed, and also, inside you can see it references your personal username "j2" so it won't work on other people's system. Nice work otherwise!

**Comment by jj9btcproj** [comment]
oops. DIdnt mean to check that file in. Removed the desktop file and replaced it with a script to make a proper desktop file with your login name and set it to make one during the python setup script.

Pretty much run the script and drag it into the launcher. You can run the setup python script to autolaunch it or remove the indicator. I will add some remove options to the indicator over the weekend

Thanks for the feedback.
